version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "order-service-log"
      POSTGRES_USER: "order-service-log"
      POSTGRES_PASSWORD: "order-service-log"
    volumes:
      - ./docker-entrypoint-initdb.d/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"